kind: pipeline
name: default
type: docker

workspace:
  path: /src

steps:
  - name: build exe
    image: cdrx/pyinstaller-windows:python3

  - name: upload release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: dist/windows
    when:
      event: tag