kind: pipeline
name: default
type: docker

steps:
  - name: install deps
    image: python:3.7
    commands:
    - pip install -r requirements.txt

  - name: build exe
    image: cdrx/pyinstaller-linux:python3
    commands:
    - pyinstaller -F --onefile --noconsole main.py

  - name: upload release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: dist
    when:
      event: tag