kind: pipeline
name: default
type: docker

workspace:
  path: /src

steps:
  - name: build exe
    image: cdrx/pyinstaller-linux:python3
    commands:
    - pyinstaller -F --onefile --noconsole main.py

  - name: upload release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: dist
    when:
      event: tag